name: Go Mod Tidy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.4'

    - name: Initialize Go Modules
      run: |
        if ! [ -f go.mod ]; then
          go mod init github.com/rhyru9/firego
        fi

    - name: Run go mod tidy
      run: |
        go mod tidy
        go mod verify
